config/routes.rb
Marysia::Application.routes.draw do

  root to: 'home#start'

  match 'start', to: 'home#start'
  match 'co', to: 'home#co'
  match 'gdzie', to: 'home#gdzie'
  match 'goscie', to: 'home#goscie'
  match 'jajecznica', to: 'home#jajecznica'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def start; end
  def co; end
  def gdzie; end
  def jajecznica; end
  def goscie; end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def smart_link_to desc, path
    klass = if path.match(params[:action])
      'active'
    end

    content_tag(:li, class: klass) { link_to desc, public_send(path) }
  end

  def smart_left_link
    destination = case params[:action]
                  when 'start'
                    jajecznica_path
                  when 'co'
                    root_path
                  when 'gdzie'
                    co_path
                  when 'goscie'
                    gdzie_path
                  when 'jajecznica'
                    goscie_path
                  end

    link_to destination do
      content_tag :i, '', class: 'icon-chevron-left'
    end
  end

  def smart_right_link
    destination = case params[:action]
                  when 'goscie'
                    jajecznica_path
                  when 'jajecznica'
                    root_path
                  when 'start'
                    co_path
                  when 'co'
                    gdzie_path
                  when 'gdzie'
                    goscie_path
                  end

    link_to destination do
      content_tag :i, '', class: 'icon-chevron-right'
    end
  end
end

app/views/home/_header.html.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container
      = link_to "Roczek Marysi", start_path, class: 'brand'
      .pull-right
        %ul.nav
          = smart_link_to "Start", 'start_path'
          = smart_link_to "Co", 'co_path'
          = smart_link_to "Gdzie", 'gdzie_path'
          = smart_link_to "Lista Gości", 'goscie_path'
          = smart_link_to "Jajecznica", 'jajecznica_path'

app/views/home/_kontakt.html.haml
.footer
  %p
    Mama z Tatą prosili, żebyście napisali im maila, czy przyjedziecie (i czy zostaniecie na noc):
    =link_to 'hajdziory@gmail.com', 'mailto:hajdziory@gmail.com'
    %br
    Piszcie też (albo dzwońcie) jeśli macie jakieś pytania
    %i.icon-smile
    (Mama: 783 680 568, Tata: 723 407 123)

app/views/home/co.html.haml
%h1.center Co się będzie działo

%p.alert
  No Mama mówi, że będę musiała zdmuchnąć ognisko i wybrać czym się będę zajmowała w dorosłym życiu (ach ta reforma szkolnictwa...)

%p Zaczynamy o 14, żeby dzieci mogły się nacieszyć dziecięcym świętem.

%p
  A dokładniej, to wszystko będzie się działo na świeżym powietrzu:
  %ul.harmonogram
    %li
      .hour 14:30
      .task Obiadek: grillowane mięsko Dziadziusia Miecia (pyycha jest!)
    %li
      .hour 16:30
      .task Ciasto Babci Bożenki (mniaam) i tort, tu chyba będę musiała coś robić, ale jeszcze nie wiem co...
    %li
      .hour 17:00 - 20:00
      .task Wy biesiadujecie, a dzieci się bawią, może wybierzemy się na spacer nad jezioro?
    %li
      .hour 20:00
      .task Dzieci już będą w objęciach Morfeusza, a dorośli zasiądą do ogniska przy dźwiękach tatusiowej i wujkowo-garetowej gitary.

= render 'kontakt'

app/views/home/gdzie.html.haml
%h1.center Gdzie i kiedy

%p.alert
  Po wejściu na przełęcz należy udać się w stronę ruin bacówki widocznych na południowy wschód od Czarnej Turni... A, nie, zaraz, nie ta wycieczka...

%p.bold  Kiedy?
%p
  15 czerwca 2013r, od godz. 14:00

%p.bold  Gdzie?
%p
  Na działce u moich Dziadków!
%p
  = link_to "Wylatkowo 51, pow. Słupecki, woj. Wielkopolskie :)", 'https://maps.google.pl/maps/ms?msid=213452247815689055104.0004ddda1bc8b0d5e3f1d&msa=0&ll=52.46375,17.925825&spn=0.034723,0.066776'
%p
  (To nie tam, gdzie lądowali kosmici, ale niedaleko!)
%p
  52° 27' 56.38" N, 17° 55' 34.15" E

%p
  W razie zgubienia szlaku dzwońcie do Taty!

= render 'kontakt'

app/views/home/goscie.html.haml
%h1.center Lista Gości

%p.alert
  Rodzice mówią, że muszę pięknie wyglądać, bo przyjedzie do mnie masa gości! Będę musiała urozmaicić moje ubranko... tylko lepiej kaszką, obiadkiem, czy jagodami? Hm...

%table
  %thead
    %th
      Starszyzna rodowa
    %th
      Młodzież rodowa
    %th
      Latorośle
    %th
      Przyjaciele
      %br
      Wesołego Diabła
  %tbody
    %tr
      %td
        %ol
          %li Babcia Bożenka
          %li Dziadziuś Jurek
          %li Babcia Gosia
          %li Dziadziuś Mieciu
          %li Prababcia Zosia
          %li Ciocia Lusia
          %li Ciocia Ula
          %li Wujek Bogdan
          %li Ciocia Aurela
          %li Ciocia Ewa 
          %li Wujek Bogdan

      %td
        %ol
          %li Ciocia Kamila
          %li Wujek Radek
          %li Ciocia Beata
          %li Wujek Sebastian
          %li Wujek Eryk
          %li Ciocia Bernadetta
          %li Wujek Konrad
          %li Wujek Mateusz
          %li Ciocia Justynka
          %li Ciocia Ania
          %li Wujek Radek
          %li Ciocia Asia
          %li Ciocia Ninka
          %li Ciocia Marysia
          %li Wujek Leszek
          %li Wujek Garret
          %li Aha! Mama
          %li No i Tata

      %td
        %ol
          %li Pola
          %li Haneczka
          %li Julka J.
          %li Jasio
          %li Julka L.
          %li Wojtek
          %li Alicja
          %li i ja, Marysia

      %td
        %ol
          %li Ciocia Medżikowa
          %li Wujek Wiśnia
          %li Ciocia Ela
          %li Ciocia Ula
          %li Wujek Tomek
          %li Antoś
          %li Wujek Adaś

= render 'kontakt'

app/views/home/jajecznica.html.haml
%h1.center Jajecznica

%p.alert Mam nadzieję, że jak najwięcej z Was zostanie do rana, bo na śniadanie będzie pyszna kaszka z Nutramigenem!

%p
  \...ewentualnie mogę poprosić Rodziców, żeby zrobili Wam jajecznicę
  %i.icon-smile

%p
  Rodzice zasięgnęli języka i okazuje się, że większości z Was możemy zaproponowac nocleg (niektórym pokój, innym łóżko, jeszcze innym materac).
  Będzie on przydzielany według starszeństwa
  %i.icon-smile

%p
  Propozycja podziału miejsc jest taka (wszystko możemy na bieząco zmieniać tak, żeby było Wam jak najwygodniej):

  %ul
    %li Babcia Bożenka i Dziadziuś Jurek: pokój u Dziadków Gosi i Miecia
    %li Ciocia Ewa i Wujek Bogdan: pokój u Dziadków Gosi i Miecia
    %li Ciocia Aurela: łóżko w salonie u Cioci Lusi
    %li Ciocia Kamila: łóżko w salonie u Cioci Lusi
    %li Wujek Garret: materac/namiot
    %li Rodzice: materac/namiot
    %li Ja: moje własne łóżeczko!
    %li
      +3 wolne łóżka u Cioci Uli dla przyjaciół
      %i.icon-smile

  Oczywiście jeśli macie ochotę, wszyscy możecie spać też w namiocie. Jeśli nie macie, Rodzice coś postarają się wykombinować
  %i.icon-smile
%p
  Jest także możliwość nocowania w gospodarstwie agroturystycznym w Wylatkowie: 
  = link_to "Agroturystyka - Bocheńscy", 'http://www.wakacjepowidz.pl'

%p
  Rodzice proszą, żebyście zabrali śpiworki (taki na przykład fajny jak mój! Pożyczyłabym Wam, ale sama w nim chyba będę spała...), albo jakieś kocyki. Jeśli nie macie, dajcie znać Rodzicom.

= render 'kontakt'

app/views/home/start.html.haml
%h1.center Roczek Marysi

%p.center
  Kochane Ciocie, Wujkowie, Kuzynki i Kuzyni!
%p.center
  Chciałabym Was zaprosić na wspólne świętowanie moich pierwszych urodzin!
%p.center
  Jeszcze nie wiem na czym to wszystko polega, ale rodzice mówią, że to fajne jest.
  %br
  I obiecują że nikt już nie będzie mnie polewał zimną wodą, tak jak na chrzcie!

%p.center.bold
  Zapraszam Was zatem
  15 czerwca 2013,
  na godz. 14:00
  do Wylatkowa!

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Marysia
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    <link href="font-awesome/css/font-awesome.css" rel="stylesheet">

%body
  .container
    = render 'home/header'
    .row
      #box
        .link
          = smart_left_link unless params[:action] == 'start'
        #main
          .photo
            = image_tag "#{params[:action]}.png", class: 'img-circle'
          .content
            = yield
        .link
          = smart_right_link unless params[:action] == 'jajecznica'